### ISSUE TITLE
I dont can install de custom component

### ISSUE THREAD

**Issue by danielandradam** [DominikWrobel/homeassistant-torque#2]
Dont can install integration

## Describe the bug
Torque Logger
Only a single instance is allowed.

**Comment by DominikWrobel** [comment]
Currently you can only have one torque logger instance, If you have two cars try using this component for one and the official HA for the other. I will try to get this to work with more then one car but I can't make any promises.

**Comment by mZer0ne** [comment]
It seems that 2 cars are working, I will check this after the Orthodox holidays

**Comment by mZer0ne** [comment]
> Dont can install integration
> 
> ## Describe the bug
> Torque Logger Only a single instance is allowed.

It seems that 2 cars are working, I will check this after the Orthodox holidays

UPDATE:
Try in torque app renaming the car profile

**Comment by danielandradam** [comment]
However this error mensage show when i try the first integration on HA...
"Only a single instance is allowed"
I dont can try integration with one car unfortully...

**Comment by DominikWrobel** [comment]
Did you delete the old version of torque logger from the integrations in HA and from HACS? Then reboot HA and try to install this version.

**Comment by DominikWrobel** [comment]
I made a version that lets you use multiple instances [https://github.com/DominikWrobel/homeassistant-torque/releases/tag/v1.4](url)

Right now I use my car only once a week, so I don't have the time to test this, so any feedback is welcome.

**Comment by danielandradam** [comment]
Hi Dominik, I just tested the new version. For configuration purposes, it is much better. I was able to configure the two vehicles with different email identifiers. However, there is a major problem! Since the PID identifiers can be the same (I imagine that's what it is), the data obtained from one vehicle is copied to the sensors of the other vehicle. In other words, the configuration is legal and independent, but the sensors are not...

**Comment by DominikWrobel** [comment]
OK, thanks for the info - I think I got this fixed in v1.4.1 [https://github.com/DominikWrobel/homeassistant-torque/releases/tag/v1.4.1](url)

It's hard to check this without testing, but like I said I can't get test this now. Thank you for the help.

**Comment by danielandradam** [comment]
Is the address in the app still the same? "https://.../api/torque_logger". Any restrictions on the email address?? Without any changes I'm getting the error message 404 on the url address in app... I'll try to restart things and test a little more later...

**Comment by DominikWrobel** [comment]
No restrictions on email adress. But I may have to look at it more and get some time to actually test it.

**Comment by danielandradam** [comment]
I've done several tests and there are still problems receiving telemetry data from two vehicles independently. When you configure just one email, it's ok, no problem... but when adding the second email, I currently receive a message from the application that it was not possible to send the data via the URL provided... Checking the documentation, I was able to identify that in the Torque application, when configuring the sending of data to a server via URL, the destination server must return an "OK" as a response to indicate that the data was received successfully. This is a standard requirement of Torque to avoid resending or errors in sending. Could it be that there is some missing configuration for this response command for the other email(s)? A suggestion to check...

Another problem with configuring more than one vehicle that identifies is the following: Initially, without starting telemetry, it is possible to include as many emails as you want independently. But if for example I add 1 email and start telemetry, then any other email added automatically copies the sensors from the first configuration. In short, the configuration of independent emails only works in the initial stage of integration without starting telemetry.

**Comment by DominikWrobel** [comment]
OK, thank you for the help. The api.py did not allow multiple instances since the api endpoint was always the same and just allowed for info from one instance. I've made changes to the api and it can be found here: [https://github.com/DominikWrobel/homeassistant-torque/releases/tag/v1.4.3](url)

I may have some time on wednesday to test it, But if you can test it sooner it would be great. 

I really don't like fixing or changing other peoples work, just wanted to have this integration working as long as I can, but at the same time maybe we can get some more functionality out of it ;)

**Comment by danielandradam** [comment]
The last versions dont working....
In version 1.3 I can obtain the data from two vehicles without any problems
The problem is that since the PIDs are practically the same, the torque logger somehow replaces the data from one vehicle in the other... in other words, only the telemetry from the last vehicle is stored at the end...
Please help...

**Comment by DominikWrobel** [comment]
As far as I can tell there is no easy way to get info from two different vehicles, the track log data from torque app does not provide vehicle indentification details, so I can't get the integration to know from which vehicle the data is from. For now you can use this integration for one car and the official integration for the other one [https://www.home-assistant.io/integrations/torque/](url)

But you will need to have a different API end point for each car (so using two different phones and apps would be the way to go).

**Comment by DominikWrobel** [comment]
I have one more idea, go to config_flow.py in version 1.3 in custom_components/torque_logger and find this:

```
        # Uncomment the next 2 lines if only a single instance of the integration is allowed:
         if self._async_current_entries():
            return self.async_abort(reason="single_instance_allowed")
```

and change this to this:

```
        # Uncomment the next 2 lines if only a single instance of the integration is allowed:
        # if self._async_current_entries():
        #    return self.async_abort(reason="single_instance_allowed")
```

Let me know if this works, maybe next week I'll have some time for testing, but no promises.

**Comment by DominikWrobel** [comment]
You can also use this app [https://play.google.com/store/apps/details?id=com.emanuelef.remote_capture](url) set the file format to PCAP and grab the the traffic from the torque app, if you have multiple cars make sure the profile names are different for each car. Then you can paste the files here.

**Comment by Failure404** [comment]
@danielandradam 
How did you solve the 404 problem with the "https://.../api/torque_logger" URL ?
